{{/* ---------------- API SERVICES ---------------- */}}
{{- if and $.Values.apps .Values.apps.api }}
{{- range $.Values.apps.api.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.Namespace }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end }}
{{- end }}


{{/* ---------------- UI SERVICES ---------------- */}}
{{- if and $.Values.apps .Values.apps.ui }}
{{- range $.Values.apps.ui.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.Namespace }}
  labels:
    app: {{ .name }}
    ui-theme: {{ $.Values.apps.ui.config.theme | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end }}
{{- end }}
