# Host cho VirtualServer
virtualServer:
  host: "todo.mahhu.io.vn"

Namespace: 'todo'

imagePullSecrets:
  - name: regcred

apps:
  ui:
    config:
      theme: dark
      enableTracking: true

    services:
      - name: todo-ui
        targetPort: 3000
        image: "harbor.mahhu.io.vn/todo/todo-app-ui"
        tag: "90"
        replicaCount: 1
        path: "/"
